---

# Firewall ---------------------------------------------------------------------
firewalld_rules:
  ssh:
    port: 22
    protocol: tcp
    state: enabled
    zone: public
    permanent: true
  http:
    port: 80
    protocol: tcp
    state: enabled
    zone: public
    permanent: true
  https:
    port: 443
    protocol: tcp
    state: enabled
    zone: public
    permanent: true

# MySQL ------------------------------------------------------------------------
mysql_root_password: "MYSQL_ROOT_PASSWORD_ON_AEGIR_SERVER"
mariadb_install_from_centos: true
mariadb_my_cnf_configuration: true
mariadb_galera_configuration: false

# Users ------------------------------------------------------------------------
user_passwordless_sudo: true
#user_authorized_keys: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
#user_authorized_keys: https://github.com/user.keys

# Aegir ------------------------------------------------------------------------
aegir_version: "3.10"
aegir_frontend_url: aegir.local
aegir_host_url: aegir.local
aegir_db_password: "MYSQL_AEGIR_USER_PASSWORD"
aegir_client_email: admin@aegir.local
# Do not enable hosting_* modules before the hosting-queued daemon, otherwise the daemon does not run.
aegir_modules_enable:
  - adminimal_admin_menu
  - module_filter
  - views_ui
aegir_modules_disable:
  - color
  - help

# Drupal console ---------------------------------------------------------------
drupal_console_keep_updated: true
drupal_console_config: false

# dot files --------------------------------------------------------------------
dotfile_users:
  - {
      name: root,
      dest: /root,
      gitname: GIT_ROOT_NAME,
      gitmail: ROOT@EMAIL
    }
  - {
      name: vagrant,
      dest: /home/vagrant,
      gitname: GIT_VAGRANT_NAME,
      gitmail: VAGRANT@EMAIL
    }
  - {
      name: aegir,
      dest: /var/aegir,
      gitname: GIT_AEGIR_NAME,
      gitmail: AEGIR@EMAIL
    }
