---

- hosts: vagrant
  become: yes
  tasks:
  - name: Build hosts file
    lineinfile:
      dest: /etc/hosts
      regexp: ".*{{ item }}$"
      line: "{{ hostvars[item].ansible_host }}\t{{ item }}"
      state: present
    when: hostvars[item].ansible_host is defined
    with_items: "{{ groups['all'] }}"
